---
title: 'Does Digital Advertising Affect Vote Choice? A Meta-analysis of the Existing and Original Field Experimental Record'
output:
  html_document:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Coppock, Alexander, Donald P. Green, Ethan Porter. 2020. Does Digital Advertising Affect Vote Choice? A Meta-analysis of the Existing and Original Field Experimental Record. Unpublished manuscript.

# Abstract
Despite the increasing sums devoted to online political advertising, our understanding of electoral effects of such advertising is limited. We report the results of a ZIP-code level randomized field experiment conducted over Facebook and Instagram during the 2018 U.S. midterm elections in Florida. The ads, produced by a Democratic-leaning political action committee, were designed to spur Democratic vote share and were seen more than 1.1 million times with over 100,000 full views. This wide saturation notwithstanding, we find that that these advertisements had very small but precisely estimated effects on Democratic vote share at the precinct level (0.0 percentage points, SE: 0.8 points). Our results underline the difficulties of political persuasion via digital advertisements, particularly in competitive electoral contexts.

# Links
 - <a href='coppock_green_porter_2020b.pdf'>Link to paper</a>

- Donald P. Green's website: https://sites.google.com/site/donaldpgreen/
- Ethan Porter's website: http://www.ethanporter.com

