---
title: "{A Field Experimental Test of Political Primes: Does the Constitution Affect Values, Vote Choice, or Turnout?}"
output:
  html_document:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Coppock, Alexander, David Kirby, Donald P. Green. 2017. <b>{A Field Experimental Test of Political Primes: Does the Constitution Affect Values, Vote Choice, or Turnout?}</b>. Unpublished manuscript.

# Abstract
Existing theory and evidence on the effects of subtle primes suggests that even small manipulations can have large and long-lasting political consequences. We conduct a massive field experiment in which 4 million Americans living in 6,057 voting precincts in six nonbattleground states were randomly assigned to be mailed either nothing or a pocket edition of the Declaration of Independence and US Constitution in advance of the 2016 presidential election. Because we doubt that subjects actually read the constitution when it is unexpectedly delivered to them, we imagine that any effects would be due to priming patriotism and shared national values. We find that, despite the enormous historical and political importance of these documents and the larger-than-usual role that pocket Constitutions played in the 2016 election, receiving the Constitution in the mail does not appear to affect subjects' values, vote choice, or turnout.

# Links
 - <a href='coppock_kirby_green_2017.pdf' target='_blank'>Link to paper</a>
 - <a href='https://osf.io/5ab4y'target='_blank'>Preanalysis plan</a>
 - <a href='https://osf.io/aqk5u'target='_blank'>Preanalysis plan 2</a>

 - <a href= 'https://www.cato.org/people/david-kirby' target='_blank'>David Kirby's website</a>
 - <a href= 'http://www.donaldgreen.com/' target='_blank'>Donald P. Green's website</a>
 - <a href='coppock_kirby_green_2017.txt'target='_blank'>Bibtex citation</a>

