---
title: "The Effects of Party Cues Are Not the Effects of Partisanship"
output:
  html_document:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Coppock, Alexander. 2025. <b>The Effects of Party Cues Are Not the Effects of Partisanship</b>. Political Science Quarterly: 1&ndash;4. <a href='https://doi.org/10.1093/psquar/qqaf037' target='_blank'>doi:10.1093/psquar/qqaf037</a>


# Abstract
In this unfortunately negative review of The Power of Partisanship, I argue that the empirical evidence offered by the authors is not relevant for their main claims about the consequences of increased affective partisanship for political and everyday life. I reanalyze their experiments to concisely convey what they do show, namely that party support cues increase policy support among in-partisans and decrease it among out-partisans. My complaint centers on the mismatch between claim and evidence. The experiments provide credible estimates of the effects of party cues, but in my opinion these estimates do not constitute evidence for the central argument of the book. 
# Links
 - <a href='coppock_2025a.pdf' target='_blank'>Link to paper</a>


 - <a href='coppock_2025a.txt'target='_blank'>Bibtex citation</a>

