---
title: "Avoiding Post-Treatment Bias in Audit Experiments"
output: 
  html_document:
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
---

Coppock, Alexander. 2019. “Avoiding Post-Treatment Bias in Audit Experiments” Journal of Experimental Political Science, 6(1), 1-4.

- [Pre-production Draft](papers/Coppock_audit_experiments.pdf)
- [Link to Journal](https://doi.org/10.1017/XPS.2018.9)
- [Replication Archive](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6NVI9C)

Audit experiments are used to easure discrimination in a large number of domains (Employment: Bertrand and Mullainathan (2004); Legislator responsiveness: Butler and Broockman (2011); Housing: Fang et al. (2018)). Audit studies all have in common that they estimate the average difference in response rates depending on randomly varied characteristics (such as the race or gender) of a requester. Scholars conducting audit experiments often seek to extend their analyses beyond the effect on response to the effects on the quality of the response. Response is a consequence of treatment; answering these important questions well is complicated by post-treatment bias (Montgomery et al., 2018). In this note, I consider a common form of post-treatment bias that occurs in audit experiments. 

## Bibtex citation

```

@article{coppock2019audit,
	Author = {Coppock, Alexander},
	Journal = {Journal of Experimental Political Science},
	Number = {1},
	Pages = {1--4},
	Title = {Avoiding Post-Treatment Bias in Audit Experiments},
	Volume = {6},
	Year = {2019}}

```
