---
title: "The effects of religious messages and endorsements on political attitudes: A meta-reanalysis"
output:
  html_document:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sarkar, Radha, Coppock, Alexander. 2026. <b>The effects of religious messages and endorsements on political attitudes: A meta-reanalysis</b>. American Political Science Review.

# Abstract
The experimental study of the effects of religious messages and endorsements by religious leaders on political attitudes has a relatively short history yet has coalesced around three main claims: religious treatments are especially effective because of their religious character, effects are larger for religious affiliates than nonaffiliates, and effects are larger for high religiosity types than low religiosity types. Here we meta re-analyze the experimental record (58 treatment-outcome pairs drawn from 43 studies reported in 26 papers) to probe the generalizability of these claims. Our findings indicate that these three headline claims do not generalize straightforwardly across contexts: effects are large in some cases and close to zero in others, and we find no evidence in favor of the claimed heterogeneities by religious affiliation or religiosity. Based on a census of the estimands in this literature, we offer suggestions for future research that would enhance commensurability and synthesis.

# Links
 - <a href='sarkar_coppock_2026.pdf' target='_blank'>Link to paper</a>
 - <a href='sarkar_coppock_2026_appendix.pdf'target='_blank'>Link to appendix</a>
 - <a href='https://doi.org/10.1017/S0003055426101695'target='_blank'>Journal site</a>
 - <a href='https://doi.org/10.7910/DVN/NHDFFS'target='_blank'>Replication archive</a>

 - <a href= 'https://research.tec.mx/vivo-tec/display/PID_503096' target='_blank'>Radha Sarkar's website</a>
 - <a href='sarkar_coppock_2026.txt'target='_blank'>Bibtex citation</a>

